obj-m           += virtio.o virtio_ring.o
obj-m           += virtio_mmio.o
obj-m           += virtio_pci.o
virtio_pci-y    := virtio_pci_modern.o virtio_pci_common.o
virtio_pci-m    += virtio_pci_legacy.o
obj-m           += virtio_net.o
obj-m           += virtio_scsi.o
